#!/usr/bin/env python3

from importlib.metadata import version

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')

from gi.repository import Gtk, Adw, Gio

# (⚠️ TODO: Load from BLP file)


@Gtk.Template(
    resource_path='/re/fossplant/pbtk/templates/main_window-autogenerated.ui'
)
class MainWindow(Adw.ApplicationWindow):
    __gtype_name__ = 'MainWindow'

    about_dialog: Adw.AboutDialog = Gtk.Template.Child()

    def __init__(self, app):
        super().__init__()

        self.set_application(app)

        # Perform data bindings

        self.bind_data()

        # Connect actions

        self.connect_actions()

        # Connect signals

        self.connect_signals()

        # Reset the default UI state

        self.reset_state()

    def bind_data(self):
        pass  # TODO

    def connect_actions(self):

        def show_about(*args):
            self.about_dialog.set_version(version('pbtk'))
            self.about_dialog.present(self)

        self.add_simple_action('show-about', show_about)

    def add_simple_action(self, name, callback, param_type=None):

        action = Gio.SimpleAction.new(name, param_type)
        action.connect('activate', callback)
        self.add_action(action)

    def connect_signals(self):
        pass  # TODO

    def reset_state(self):
        pass  # TODO
