#!/usr/bin/env python3

from pbtk.gtk.templates.extractor_row import ExtractorRow
from pbtk.utils.common import extractors, BASE_PATH
from pbtk.gtk.datamodel.extractor import Extractor
from pbtk.extractors import *

from importlib.metadata import version

import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')

from gi.repository import Gtk, Adw, GObject, Gio

# (⚠️ TODO: Load from BLP file)


@Gtk.Template(
    resource_path='/re/fossplant/pbtk/templates/main_window-autogenerated.ui'
)
class MainWindow(Adw.ApplicationWindow):
    __gtype_name__ = 'MainWindow'

    about_dialog: Adw.AboutDialog = Gtk.Template.Child()

    main_nav_view: Adw.NavigationView = Gtk.Template.Child()

    open_dir_section: Adw.PreferencesGroup = Gtk.Template.Child()

    extractor_objs = GObject.Property(type=Gio.ListStore)  # Of Extractor
    extractors_list: Adw.PreferencesGroup = Gtk.Template.Child()

    extracting_status_page: Adw.StatusPage = Gtk.Template.Child()
    extraction_spinner: Adw.SpinnerPaintable = Gtk.Template.Child()
    extracting_progress_bar: Gtk.ProgressBar = Gtk.Template.Child()
    extraction_next_steps: Gtk.Box = Gtk.Template.Child()
    extraction_text_view: Gtk.TextView = Gtk.Template.Child()
    extraction_text_buffer: Gtk.TextBuffer = Gtk.Template.Child()

    global_extraction_dir = GObject.Property(type=str)

    def __init__(self, app):
        super().__init__()

        self.set_application(app)

        # Perform data bindings

        self.bind_data()

        # Connect actions

        self.connect_actions()

        # Connect signals

        self.connect_signals()

        # Reset the default UI state

        self.reset_state()

    def bind_data(self):
        self.global_extraction_dir = str(BASE_PATH / 'protos')

        self.open_dir_section.set_description(
            ('Location: %s') % self.global_extraction_dir
        )

        self.extractor_objs = Gio.ListStore.new(Extractor)

        for name, extractor_obj in extractors.items():
            self.extractor_objs.append(extractor_obj)

        self.extractors_list.bind_model(
            self.extractor_objs, ExtractorRow, self
        )

        # 🪧➡️ WIP ⚠️: BIND EXTRACTORS LIST TO UI PANEL #1
        # Cf. https://lazka.github.io/pgi-docs/Adw-1/classes/PreferencesGroup.html#Adw.PreferencesGroup.bind_model

    def connect_actions(self):

        def show_about(*args):
            self.about_dialog.set_version(version('pbtk'))
            self.about_dialog.present(self)

        self.add_simple_action('show-about', show_about)

        def open_proto_dir(*args):
            proto_dir = Gio.File.new_for_path(self.global_extraction_dir)
            Gtk.FileLauncher.new(proto_dir).launch(self, None, None)

        self.add_simple_action('open-proto-dir', open_proto_dir)

        def go_back_to_main(*args):
            self.main_nav_view.pop_to_tag('main_page')

        self.add_simple_action('go-back-to-main', go_back_to_main)

    def add_simple_action(self, name, callback, param_type=None):

        action = Gio.SimpleAction.new(name, param_type)
        action.connect('activate', callback)
        self.add_action(action)

    def connect_signals(self):
        pass  # TODO

    def reset_state(self):
        pass  # TODO
